LIKWID_INC ?= -I${LIKWID_INCDIR}
LIKWID_DEFINES ?= -DLIKWID_PERFMON
LIKWID_LIB ?= -L${LIKWID_LIBDIR}

ifeq ($(strip $(ENABLE_LIKWID)),true)
INCLUDES += ${LIKWID_INC}
DEFINES +=  ${LIKWID_DEFINES}
LIBS += -llikwid
LFLAGS += ${LIKWID_LIB}
endif
